### PR TITLE
System to translate generated API reference

### PR DESCRIPTION
**Pull request by feloy**
Fixes https://github.com/kubernetes/website/issues/27841

This PR is a proposition of a system to translate the API reference generated by `gen-resourcesdocs`.

The system is based on the `gettext` tools.

- An operation is added to the `gen-resourcesdocs` program to create POT files from the swagger definition and the sources of the program (and more as necessary)
- the translation teams create PO files based on the POT files generated
- these PO files are translated, and MO files are generated
- when the generator builds the API reference pages, it gets the available translations from MO files.

See https://github.com/kubernetes-sigs/reference-docs/pull/232/files#diff-5b35ef372b4657dea2d429dcdfd800f352ba63ce041cd322f5a778140f9e5423 for more details

Example of translated page: https://deploy-preview-27842--kubernetes-io-master-staging.netlify.app/fr/docs/reference/kubernetes-api/workload-resources/job-v1/

### CODE REVIEW

**Comment by kbhawkey** [comment]
👀

**Comment by sftim** [comment]
Eventually / before launch, we'd move the `.po` files into https://github.com/kubernetes/website/ (I'm assuming). Is that right?

**Comment by feloy** [comment]
> Eventually / before launch, we'd move the `.po` files into https://github.com/kubernetes/website/ (I'm assuming). Is that right?

Yes, you're right.

I'm also wondering in the following issue if we could move the files needed to create the API reference in the kubernetes/website repository: #230

**Comment by jimangel** [comment]
This is awesome work, but I'll differ to the tech leads to assist with review / approval. Otherwise LGTM! 🎉

**Comment by sftim** [comment]
(nit)
/retitle System to translate generated API reference

**Comment by sftim** [comment]
I'd like to help with https://github.com/kubernetes-sigs/reference-docs/pull/232#issuecomment-857936490 - making sure that the `.po` files are available within https://github.com/kubernetes/website/ for localization teams to collaborate on translating etc.

**Comment by sftim** [comment]
/hold
in case a stray /lgtm gets this merged too early. The approval stands: we should add this mechanism.

**Comment by jimangel** [comment]
@feloy @sftim what is left to complete this PR / review?

**Comment by feloy** [comment]
> @feloy @sftim what is left to complete this PR / review?

I first would like to move the translated contents files to the Kubernetes/website repository, as it has been done on this PR (https://github.com/kubernetes/website/pull/29217) for the assets of the API reference

**Pull request closed without merging**
