### PR TITLE
updates to build 1.20 references

### PR DESCRIPTION
**Pull request by kbhawkey**
- Removed cloud-controller-manager from build target
- Created configuration for v1.19 and v1.20
- Update kubectl command toc.yaml (removed convert, added debug)

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
As this is for v1.20 @kbhawkey can you confirm that files such as `gen-kubectldocs/generators/v1_19/static_includes/_app_management.md` supposed to be part of this change?

**Comment by sftim** [comment]
Maybe the v1.19 change could be a separate commit to make that more obvious?

**Comment by kbhawkey** [comment]
Yes, I ran the Makefile twice (1.19 and 1.20) to generate the configuration files (target createversiondirs).
The script relies upon a previous configuration to generate the next configuration and does not default to any configuration file.
The 1.19 build used the 1.18 configuration (generates dynamically in the build sandbox but does not commit).
I never got around to generating and merging a 1.19 configuration. I did this now.
I have not read through the API configuration. The API reference will need code/config updates.

**Comment by kbhawkey** [comment]
I have not looked at updating the API generator/config to address issue #178.

**Comment by kbhawkey** [comment]
There is one more error to resolve for `v1alpha1/storageversions`.
/cc @tengqm

**Comment by tengqm** [comment]
/lgtm
/approve

> There is one more error to resolve for v1alpha1/storageversions.

I'll check it.

**Comment by tengqm** [comment]
@kbhawkey Fix is proposed in #181

**Pull request merged**
