### PR TITLE
Backport changes to release-1.16

### PR DESCRIPTION
**Pull request by tengqm**
This PR backports some changes on master to the release-1.16 branch, namely #110, #114, #115, #116.

### CODE REVIEW

**Comment by kbhawkey** [comment]
The release-1.16 branch will be used to reproduce the API ref or not?

**Comment by tengqm** [comment]
@kbhawkey We took a snapshot when fixing the API ref generator for 1.17. The snapshot starts the release-1.16 branch, in case we need to regenerate the API ref for whatever reason. Since we have reworked the directory layout for gen-apidocs, we are only porting back some bug fixes manually.

I have already regenerated the 1.16 API ref to fix an issue found at k8s/website. (https://github.com/kubernetes/website/pull/18587).

**Comment by kbhawkey** [comment]
> 
> 
> @kbhawkey We took a snapshot when fixing the API ref generator for 1.17. The snapshot starts the release-1.16 branch, in case we need to regenerate the API ref for whatever reason. Since we have reworked the directory layout for gen-apidocs, we are only porting back some bug fixes manually.
> 
> I have already regenerated the 1.16 API ref to fix an issue found at k8s/website. ([kubernetes/website#18587](https://github.com/kubernetes/website/pull/18587)).

OK, was news to me.

**Pull request merged**
