### PR TITLE
update docsy-example theme submodule, .gitignore, travis build target

### PR DESCRIPTION
**Pull request by kbhawkey**
Verify gen-resourcesdocs builds.
Add gen-resourcesdocs/kwebsite to `.gitignore`.

### CODE REVIEW

**Review by onlydole — APPROVED** [review]
LGTM, thank you, @kbhawkey! 

/lgtm

**Comment by kbhawkey** [comment]
I'd like to see the build complete
/hold

**Comment by kbhawkey** [comment]
I will fix/update the docsy_example and theme.

**Comment by kbhawkey** [comment]
Tested locally with `hugo server`.

**Comment by kbhawkey** [comment]
The build is looking better.

**Pull request merged**
