### PR TITLE
update module name

### PR DESCRIPTION
**Pull request by kbhawkey**
Testing an `<hr>` element after type description.

### CODE REVIEW

**Comment by tengqm** [comment]
@kbhawkey Pls remove (wip) when this is ready.

**Comment by kbhawkey** [comment]
The source builds. I am looking for feedback on the addition of the `<hr>` element.

**Comment by tengqm** [comment]
/approve

The addition of `<hr/>` looks good to me too.

Thanks.

**Comment by feloy** [comment]
The use of hr looks good to me

**Pull request merged**
