### PR TITLE
Add outputs from genref tool

### PR DESCRIPTION
**Pull request by tengqm**
I'm proposing a version control for the config outputs because:

- We want to know how frequent the upstream config structs are changed;
- The config files (HTML plus MD) are not huge assets to manage;
- We can later decide to remove this from version control when we gain
  more confidence about the generator and the workflow.

These files are separated from the PR #176 to ease the PR review.

### CODE REVIEW

**Comment by tengqm** [comment]
/hold

this PR depends on #176.

**Comment by kbhawkey** [comment]
👋 @tengqm .
I'd like more information about storing the generated files in this repository.
Will you tag or reference a specific commit after the files are generated (at release time)?
Will you replace the files every release or when the upstream files change?

**Comment by tengqm** [comment]
> Will you tag or reference a specific commit after the files are generated (at release time)?
The outputs are supposed to be regenerated at each release, in a similar way how we have been handling kube- components.

> Will you replace the files every release or when the upstream files change?
The current plan is to replace the files every release.

> Will you save both Markdown and HTML versions of the files?
For markdown version, it is designed to be fed to the website. The HTML version is for local preview. I don't have a good solution to preview markdown locally as web pages.

> How many files are currently published?
Currently, there are 7 files proposed to k/website. We may need to maintain about 10 config API files eventually.

> Will you add the build of the tool to the base Makefile in this repository (and add to travis)?
Yes. That is the plan.

**Comment by kbhawkey** [comment]
Hi. I added the docsy theme to this repository. It should help to evaluate newly rendered pages.
Let me know if the sub module is not set up correctly.
If you run `git submodule update --init --recursive --depth 1`, the theme should install.
You could copy the generated files to the reference section/add to the content tree, and test?

**Comment by tengqm** [comment]
@kbhawkey Good idea. Will try.

**Comment by kbhawkey** [comment]
Should be docsy-example. There is a `References` section.

**Comment by tengqm** [comment]
The submodule command doesn't work for me. Tried several ways to work around it but failed.

```
docsy-example $ git submodule update --init --recursive --depth 1
fatal: No url found for submodule path 'themes/docsy' in .gitmodules
```

**Comment by kbhawkey** [comment]
> 
> 
> The submodule command doesn't work for me. Tried several ways to work around it but failed.
> 
> ```
> docsy-example $ git submodule update --init --recursive --depth 1
> fatal: No url found for submodule path 'themes/docsy' in .gitmodules
> ```

OK. This is not working as expected. The "docsy-example" is not a sub-module. The theme is.
I was trying to add a "test" hugo site into this repository.
Newly generated reference pages could be copied into this content tree for testing.
I'll look into what's there now and see if I can sort it out.

**Comment by tengqm** [comment]
/hold cancel
The generator is now in.

**Comment by tengqm** [comment]
/hold
Holding this again because we may want to get #214, #215 in first.

**Comment by tengqm** [comment]
/hold cancel
Removing hold because #176 is in.

**Comment by tengqm** [comment]
/hold
Hold again because this is now depending on #215

**Comment by kbhawkey** [comment]
These changes look ready?
/lgtm
Remove hold if ready.
Thanks @tengqm 
/hold

**Pull request merged**
