### PR TITLE
gen-compdocs: update to 1.23.0

### PR DESCRIPTION
**Pull request by pohly**
This is currently the latest release. Something like this PR should be needed to update https://github.com/kubernetes/website/commits/dev-1.23/content/en/docs/reference/command-line-tools-reference/

If not, feel free to close it.

### CODE REVIEW

**Comment by kbhawkey** [comment]
@pohly , Is it okay if we close this PR? The 1.23.0 release tag is available. Thanks.

**Comment by pohly** [comment]
Doesn't someone still need to update the command line tools reference for 1.23? The last update seems to be for 1.22:

https://github.com/kubernetes/website/commits/dev-1.23/content/en/docs/reference/command-line-tools-reference/kube-apiserver.md

If yes, then a PR like this will be needed.

**Comment by tengqm** [comment]
@pohly I think @kbhawkey has already updated the build facilities for kubectl? https://github.com/kubernetes-sigs/reference-docs/pull/266

**Comment by pohly** [comment]
> I think @kbhawkey has already updated the build facilities for kubectl?

Yes. But isn't this directory for the other tools (kube-controller-manager, kube-proxy, etc.)?

**Comment by kbhawkey** [comment]
> > I think @kbhawkey has already updated the build facilities for kubectl?
> 
> Yes. But isn't this directory for the other tools (kube-controller-manager, kube-proxy, etc.)?

Hi @pohly . Yes, PR https://github.com/kubernetes-sigs/reference-docs/pull/264 updates the go.mod and go.sum files for the gen-compdocs build. Does this make sense?

**Comment by pohly** [comment]
This PR is not needed anymore because https://github.com/kubernetes-sigs/reference-docs/pull/264 got merged instead.

/close

**Comment by tengqm** [comment]
@pohly Thanks for your help anyway.

**Pull request closed without merging**
