### PR TITLE
add feloy as reviewer/approver

### PR DESCRIPTION
**Pull request by kbhawkey**
Add @feloy to OWNERS file.

### CODE REVIEW

**Comment by kbhawkey** [comment]
/hold for review
@feloy has contributed the new resources generator and is a core reference documentation contributor.

**Comment by kbhawkey** [comment]
Looks like I am missing a step in this process.

**Comment by zacharysarah** [comment]
@kbhawkey 👋🏻 
> Looks like I am missing a step in this process.

Based on [the bot reply](https://github.com/kubernetes-sigs/reference-docs/pull/194#issuecomment-754914645), I think @feloy needs to [join the `kubernetes-sigs` org](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) before he can be an OWNER.

**Comment by feloy** [comment]
@zacharysarah @kbhawkey can you sponsor me to join the kubernetes-sigs org?

**Comment by zacharysarah** [comment]
@feloy 
> can you sponsor me to join the kubernetes-sigs org?

Gladly. 👍🏻

**Comment by kbhawkey** [comment]
> can you sponsor me to join the kubernetes-sigs org?

@feloy, Yes, that's great!

**Comment by feloy** [comment]
I've created the issue to join kubernetes-sigs: https://github.com/kubernetes/org/issues/2404

**Comment by jimangel** [comment]
My approval [here](https://github.com/kubernetes-sigs/reference-docs/pull/171#issuecomment-761721622) created a conflict, sorry @kbhawkey. Once conflict is resolved this is good to go!

/lgtm
/approve

**Pull request merged**
