### PR TITLE
Make sure API responses are sorted

### PR DESCRIPTION
**Pull request by tengqm**
xref: #126

### CODE REVIEW

**Comment by kbhawkey** [comment]
See my comments from PR #126

**Comment by tengqm** [comment]
@kbhawkey Yes we have a release-1.16 branch for regenerating the 1.16 references. This PR contains an improvement to master, which is also proposed to release-1.16. The idea behind this PR was triggered by a previous commit (https://github.com/kubernetes/website/pull/18466/files#diff-f333bc8f279559f54f72b1ac02c65cecR7317) where you can see many diffs are actually fake changes. The order of the response records was different.

**Comment by kbhawkey** [comment]
@tengqm , I think you mean that duplication of content was added into the generated reference (not really faked by a human or added manually).

**Comment by tengqm** [comment]
Yes. It is not a bug in the strict sense. But having responses yielded in different orders each time is not good.

**Comment by kbhawkey** [comment]
> 
> 
> Yes. It is not a bug in the strict sense. But having responses yielded in different orders each time is not good.

OK, got it.
/lgtm

**Pull request merged**
